services:
  notmg:
    build: ./.
    ports:
      - "127.0.0.1:4445:4444"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/notmg_prod.db
      - SECRET_KEY_BASE=this-is-a-secret-key-base-that-is-more-than-64-bytes-therefore-i-have-to-keep-typing-this-text-to-make-it-longer
      - PHX_HOST=localhost
